[cosmology]
h = 0.6736
Omega_b = 0.0493
Omega_cdm = 0.2645
Omega_m = 0.3138
n_s = 0.9649
A_s = 2.1e-9
tau_reio = 0.0544
T_cmb = 2.7255
sigma_8 = 0.8111
Pk_ini_type = analytic_Pk 
#command = cat power_spectrum_Mpc.dat

[script]
zeta = 25
log10_Mmin = 8
ngrid = 32
helium_factor = 1.0789
helium_factor_lowz = 1.1578